"""empty message

Revision ID: 2ecb775be473
Revises: 9b3bac7417e6
Create Date: 2025-04-01 08:31:25.233071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb775be473'
down_revision = '9b3bac7417e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_defined_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disk', sa.String(length=120), nullable=False))
        batch_op.drop_column('hdd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_defined_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hdd', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('disk')

    # ### end Alembic commands ###
