"""empty message

Revision ID: 5b397bb50b5a
Revises: 3ef617fb776c
Create Date: 2025-04-03 15:01:05.138122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b397bb50b5a'
down_revision = '3ef617fb776c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
