"""empty message

Revision ID: 9504451a88af
Revises: 2ecb775be473
Create Date: 2025-04-01 08:37:07.032652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9504451a88af'
down_revision = '2ecb775be473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_defined_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_column('nombre_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_defined_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_plan', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
