"""empty message

Revision ID: 9b3bac7417e6
Revises: 
Create Date: 2025-03-27 09:48:30.767967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3bac7417e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.Column('rif', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('pre_defined_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(length=80), nullable=False),
    sa.Column('ram', sa.String(length=120), nullable=False),
    sa.Column('hdd', sa.String(length=120), nullable=False),
    sa.Column('processor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('request_no_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('selected_os', sa.String(length=80), nullable=True),
    sa.Column('custom_os', sa.String(length=80), nullable=True),
    sa.Column('ram', sa.String(length=80), nullable=True),
    sa.Column('disk', sa.String(length=80), nullable=True),
    sa.Column('processors', sa.String(length=80), nullable=True),
    sa.Column('network', sa.String(length=80), nullable=True),
    sa.Column('network_adapter', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_user', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_password', sa.String(length=80), nullable=True),
    sa.Column('ssh_keys', sa.Text(), nullable=True),
    sa.Column('resource_group', sa.String(length=80), nullable=True),
    sa.Column('storage', sa.String(length=80), nullable=True),
    sa.Column('template_or_iso', sa.String(length=80), nullable=True),
    sa.Column('disk_type', sa.String(length=80), nullable=True),
    sa.Column('storage_policy', sa.String(length=80), nullable=True),
    sa.Column('guest_os_customization', sa.String(length=80), nullable=True),
    sa.Column('high_availability', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.String(length=80), nullable=True),
    sa.Column('snapshot_policy', sa.String(length=80), nullable=True),
    sa.Column('vm_type', sa.String(length=80), nullable=True),
    sa.Column('disk_format', sa.String(length=80), nullable=True),
    sa.Column('bios_or_uefi', sa.String(length=80), nullable=True),
    sa.Column('cloud_init', sa.String(length=80), nullable=True),
    sa.Column('numa', sa.String(length=80), nullable=True),
    sa.Column('backup_schedule', sa.String(length=80), nullable=True),
    sa.Column('hotplug', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['final_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_pre_defined_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('selected_os', sa.String(length=80), nullable=True),
    sa.Column('custom_os', sa.String(length=80), nullable=True),
    sa.Column('network', sa.String(length=80), nullable=True),
    sa.Column('network_adapter', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_user', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_password', sa.String(length=80), nullable=True),
    sa.Column('ssh_keys', sa.Text(), nullable=True),
    sa.Column('resource_group', sa.String(length=80), nullable=True),
    sa.Column('storage', sa.String(length=80), nullable=True),
    sa.Column('template_or_iso', sa.String(length=80), nullable=True),
    sa.Column('disk_type', sa.String(length=80), nullable=True),
    sa.Column('storage_policy', sa.String(length=80), nullable=True),
    sa.Column('guest_os_customization', sa.String(length=80), nullable=True),
    sa.Column('high_availability', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.String(length=80), nullable=True),
    sa.Column('snapshot_policy', sa.String(length=80), nullable=True),
    sa.Column('vm_type', sa.String(length=80), nullable=True),
    sa.Column('disk_format', sa.String(length=80), nullable=True),
    sa.Column('bios_or_uefi', sa.String(length=80), nullable=True),
    sa.Column('cloud_init', sa.String(length=80), nullable=True),
    sa.Column('numa', sa.String(length=80), nullable=True),
    sa.Column('backup_schedule', sa.String(length=80), nullable=True),
    sa.Column('hotplug', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['final_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['pre_defined_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_maquina', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_no_catalog_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_pre_defined_plans.id'], ),
    sa.ForeignKeyConstraint(['request_no_catalog_id'], ['request_no_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_machines')
    op.drop_table('request_pre_defined_plans')
    op.drop_table('request_no_catalog')
    op.drop_table('user')
    op.drop_table('pre_defined_plans')
    op.drop_table('final_user')
    # ### end Alembic commands ###
