"""empty message

Revision ID: a5aa16e0d175
Revises: 
Create Date: 2025-04-03 12:37:54.540500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5aa16e0d175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.Column('rif', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('hypervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('vcenter', 'proxmox', name='hypervisor_type'), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_defined_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ram', sa.String(length=120), nullable=False),
    sa.Column('disk', sa.String(length=120), nullable=False),
    sa.Column('processor', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('vm_creation_status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('hypervisor_id', sa.Integer(), nullable=False),
    sa.Column('selected_os', sa.String(length=80), nullable=True),
    sa.Column('custom_os', sa.String(length=80), nullable=True),
    sa.Column('network', sa.String(length=80), nullable=True),
    sa.Column('network_adapter', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_user', sa.String(length=80), nullable=True),
    sa.Column('os_credentials_password', sa.String(length=80), nullable=True),
    sa.Column('ssh_keys', sa.Text(), nullable=True),
    sa.Column('resource_group', sa.String(length=80), nullable=True),
    sa.Column('storage', sa.String(length=80), nullable=True),
    sa.Column('template_or_iso', sa.String(length=80), nullable=True),
    sa.Column('disk_type', sa.String(length=80), nullable=True),
    sa.Column('storage_policy', sa.String(length=80), nullable=True),
    sa.Column('guest_os_customization', sa.String(length=80), nullable=True),
    sa.Column('high_availability', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.String(length=80), nullable=True),
    sa.Column('snapshot_policy', sa.String(length=80), nullable=True),
    sa.Column('vm_type', sa.String(length=80), nullable=True),
    sa.Column('disk_format', sa.String(length=80), nullable=True),
    sa.Column('bios_or_uefi', sa.String(length=80), nullable=True),
    sa.Column('cloud_init', sa.String(length=80), nullable=True),
    sa.Column('numa', sa.String(length=80), nullable=True),
    sa.Column('backup_schedule', sa.String(length=80), nullable=True),
    sa.Column('hotplug', sa.Boolean(), nullable=True),
    sa.Column('ram', sa.String(length=80), nullable=True),
    sa.Column('disk', sa.String(length=80), nullable=True),
    sa.Column('processors', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['final_user.id'], ),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisor.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['pre_defined_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_table('virtual_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_maquina', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('creation_status', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('hypervisor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('external_vm_id', sa.String(length=255), nullable=True),
    sa.Column('external_vm_name', sa.String(length=255), nullable=True),
    sa.Column('external_vm_power_state', sa.String(length=50), nullable=True),
    sa.Column('external_vm_guest_os', sa.String(length=255), nullable=True),
    sa.Column('external_vm_ip_address', sa.String(length=120), nullable=True),
    sa.Column('external_vm_cpu_count', sa.Integer(), nullable=True),
    sa.Column('external_vm_memory_mb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisor.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('hypervisor_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisor.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_log')
    op.drop_table('virtual_machines')
    op.drop_table('request')
    op.drop_table('user')
    op.drop_table('pre_defined_plans')
    op.drop_table('hypervisor')
    op.drop_table('final_user')
    # ### end Alembic commands ###
