"""empty message

Revision ID: c3f480025b2f
Revises: 5b397bb50b5a
Create Date: 2025-04-04 14:45:32.239922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f480025b2f'
down_revision = '5b397bb50b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('authorization_endpoint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_endpoint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('redirect_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('scope')
        batch_op.drop_column('redirect_uri')
        batch_op.drop_column('token_endpoint')
        batch_op.drop_column('authorization_endpoint')
        batch_op.drop_column('client_secret')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
