"""empty message

Revision ID: cff95a0aa83a
Revises: 9504451a88af
Create Date: 2025-04-01 10:56:15.290758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff95a0aa83a'
down_revision = '9504451a88af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('vcenter', 'proxmox', name='hypervisor_type'), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('hypervisor_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisor.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hypervisor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_vm_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_vm_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_vm_power_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_vm_guest_os', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_vm_ip_address', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('external_vm_cpu_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_vm_memory_mb', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hypervisor', ['hypervisor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('external_vm_memory_mb')
        batch_op.drop_column('external_vm_cpu_count')
        batch_op.drop_column('external_vm_ip_address')
        batch_op.drop_column('external_vm_guest_os')
        batch_op.drop_column('external_vm_power_state')
        batch_op.drop_column('external_vm_name')
        batch_op.drop_column('external_vm_id')
        batch_op.drop_column('hypervisor_id')

    op.drop_table('operation_log')
    op.drop_table('hypervisor')
    # ### end Alembic commands ###
